---
version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: friday
      time: "08:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
